### ISSUE TITLE
Unable to build on Windows 11 with Node.js v18.12.0 due to  code: 'ERR_OSSL_EVP_UNSUPPORTED'

### ISSUE THREAD

**Issue by bogdan192** [FriedChickenButt/youtube-webos#40]
When attempting to build on WIndows 11 22H2 with node v18.12.0 I get the following error:
```
> youtube-webos@0.0.2 build
> webpack

Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\util\createHash.js:145:18)
    at BulkUpdateDecorator.update (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\util\createHash.js:46:50)
    at RawSource.updateHash (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack-sources\lib\RawSource.js:64:8)
    at NormalModule._initBuildHash (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\NormalModule.js:870:17)
    at handleParseResult (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\NormalModule.js:936:10)
    at C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\NormalModule.js:1028:4
    at processResult (C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\NormalModule.js:745:11)
    at C:\Users\UserXP\Desktop\youtube-webos\youtube-webos\node_modules\webpack\lib\NormalModule.js:809:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.12.0
```

**Comment by TheSweppy** [comment]
I was able to fix it by first typing:
npx browserslist@latest --update-db

and then:
SET NODE_OPTIONS=--openssl-legacy-provider

after that run the build command again.

Hope that helps.
